---

- hosts: all
  become: true
  tasks: 

  - name: create simone user  
    user:
      name: simone
      groups: root

  - name: add ssh key for simone
    authorized_key:
      user: simone
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDCwqlTE5fIod13044UCTHPjPaitUsxCt8zNJ9silSal ansible"

  - name: add sudoers file for simone
    copy:
      src: sudoer_simone
      dest: /etc/sudoers.d/simone
      owner: root
      group: root
      mode: 0440
