---

- hosts: all
  become: true
  tasks: 

  - name: create simone user  
    user:
      name: simone
      groups: root

  - name: add sudoers file for simone
    copy:
      src: sudoer_simone
      dest: /etc/sudoers.d/simone
      owner: root
      group: root
      mode: 0440

- hosts: all 
  become: true
  roles:
    - base
